routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('videos', 'VideoController');
Route::post('videos/{video}', 'VideoController@update')->name('videos.update');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use App\Video;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Relationships
    public function video()
    {
        return $this->hasMany(Video::class);
    }
}

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Video;

class Video extends Model
{
    //Relationships
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;
use FFMpeg;

use Auth;

use App\Video;
use Illuminate\Http\Request;
use Carbon\Carbon;

class VideoController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = Auth::user()->video;
        return view('videos')->with('videos', $videos);
    }


    public function all()
    {
        $videos = Auth::user()->video;
        return $videos;
    }

    public function search(Request $request)
    {
        $search = Video::where('name', 'like', '%'.$request['title'].'%')->get();
        return $data = ['result' => $search];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('upload');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      if($request->hasFile('video')){


        $this->validate($request, [
            'video' => 'required|mimes:mp4,webm,avi,flv|max:500000',
        ]);

          $file = $request->file('video');
          $time = time();
          $videoFileName = $time . '.' . $file->getClientOriginalExtension();

          // Get Duration;
          $ffprobe = FFMpeg\FFProbe::create(
            [
              'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe', // the path to the FFMpeg binary
              'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe', // the path to the FFProbe binary
            ]
          );

          $duration = $ffprobe
              ->format($file) // extracts file informations
              ->get('duration');

          $durationFormat = gmdate("i:s", round($duration));

          $filename = $file->getClientOriginalName();
          $filenamenoExt = pathinfo($filename, PATHINFO_FILENAME);
          $path = public_path().'/uploads/';
          $filepath = $file->move($path, $videoFileName);

          // Get Thumbnail
          $ffmpeg = FFMpeg\FFMpeg::create(
            [
              'ffmpeg.binaries'  => 'C:/FFmpeg/bin/ffmpeg.exe', // the path to the FFMpeg binary
              'ffprobe.binaries' => 'C:/FFmpeg/bin/ffprobe.exe', // the path to the FFProbe binary
            ]
          );
          $frameName = 'thumbnails/'.$time.'.jpg';
          $video = $ffmpeg->open($filepath);
          $video
              ->filters()
              ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
              ->synchronize();
          $video
              ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(10))
              ->save($frameName);
          $newVideo = new Video();
          $newVideo->user_id = Auth::user()->id;
          $newVideo->name = $filenamenoExt;
          $newVideo->time_name = $videoFileName;
          $newVideo->duration = $durationFormat;
          $newVideo->thumb = $frameName;
          $newVideo->save();
          return redirect('videos');
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        // return 'pop';
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        return view('edit')->with('video', $video);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Video $video)
    {
      // return $video;
        $video->name = $request->name;
        $video->desc = $request->desc;
        $video->tags = $request->tags;
        $video->category = $request->category;
        $video->save();
        return redirect('videos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy(Video $video)
    {
      // return $video;
        // $video = Video::find($video);
        unlink($video['thumb']);
        unlink('uploads/'.$video['time_name']);
        $video->delete();

        return $data = ['status' => 'success'];
    }
}

resources/views/edit.blade.php
@extends('layouts.app')
@include('layouts.sidebar')
@section('content')
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
          <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Metadata</h4>

                                    <form method="POST" action="{{ route('videos.update', $video['id']) }}">
                                      @csrf
                                          <div class="form-group">
                                              <label for="name">Name</label>
                                              <input type="text" id="name" name="name" class="form-control" placeholder="Title" value="{{ $video['name'] }}">
                                          </div>

                                          <div class="form-group">
                                              <label for="desc">Description</label>
                                              <textarea name="desc" id="desc" class="form-control" rows="5" cols="80">{{ $video['desc'] }}</textarea>
                                          </div>

                                          <div class="form-group">
                                              <label for="tags">Tags</label>
                                              <input type="text" class="form-control" name="tags" id="tags" placeholder="Tags" value="{{ $video['tags'] }}">
                                          </div>
                                          <div class="form-group">
                                              <label for="category">Categories</label>
                                              <input type="text" name="category" class="form-control" id="category" placeholder="Categories" value="{{ $video['category'] }}">
                                          </div>
                                    @if ($errors->has('video'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('video') }}</strong>
                                        </span>
                                        <br>
                                    @endif
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                    <a href="{{ route('videos.index') }}"><button type="button" class="btn btn-danger waves-effect waves-light">Close</button></a>
                                    </form>

                                </div> <!-- end card body-->
                            </div> <!-- end card -->
                        </div><!-- end col-->
                    </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
{{-- <script src="{{ asset('js/metismenu.min.js') }}"></script>
<script src="{{ asset('js/waves.js') }}"></script> --}}
{{-- <script src="{{ asset('js/simplebar.min.js') }}"></script> --}}

<!-- third party js -->
        <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.flash.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.keyTable.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.select.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="{{ asset('pages/datatables-demo.js') }}"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Vidgyor') }}</title>

    <!-- Scripts -->

    <!-- App css -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/theme.min.css') }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
     <link href="{{ asset('plugins/datatables/responsive.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
     <link href="{{ asset('plugins/datatables/buttons.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
     <link href="{{ asset('plugins/datatables/select.bootstrap4.css') }}" rel="stylesheet" type="text/css" />

</head>
<body>
      <header id="page-topbar">
            <div class="navbar-header">
                <!-- LOGO -->
                <div class="navbar-brand-box d-flex align-items-left">
                    <a href="{{ config('app.url') }}" class="logo">
                        {{-- <span>
                            <img src="{{ asset('images/logo-light.png') }}" alt="" height="18">
                        </span>
                        <i>
                            <img src="{{ asset('images/logo-small.png') }}" alt="" height="24">
                        </i> --}}
                    </a>

                    <button type="button" class="btn btn-sm mr-2 d-lg-none px-3 font-size-16 header-item waves-effect waves-light" id="vertical-menu-btn">
                        <i class="fa fa-fw fa-bars"></i>
                    </button>
                </div>

                <div class="d-flex align-items-center">




                    <div class="dropdown d-inline-block ml-2">
                            @guest
                              <span class=""><a class="text-white" href="{{ route('login') }}">Login</a></span>
                              &nbsp;&nbsp;&nbsp;
                              <span class=""><a class="text-white" href="{{ route('register') }}">{{ __('Register') }}</a></span>

                            @else
                              <button type="button" class="btn header-item waves-effect waves-light" id="page-header-user-dropdown"
                              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="d-none d-sm-inline-block ml-1">{{ Auth::user()->name }}</span>
                            <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                          </button>
                            @endguest
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item d-flex align-items-center justify-content-between" href="{{ route('logout') }}"
                             onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                              <span>{{ __('Logout') }}</span>
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                        </div>
                    </div>

                </div>
            </div>
        </header>



        {{-- <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Vidgyor') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav> --}}

            @yield('content')
</body>
</html>

resources/views/layouts/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>
                <li>
                    <a href="{{ route('videos.index') }}" class="waves-effect"><i class="mdi mdi-view-dashboard"></i><span>Videos</span></a>
                </li>
                <li>
                    <a href="{{ route('videos.create') }}" class="waves-effect"><i class="mdi mdi-view-dashboard"></i><span>Add Video</span></a>
                </li>






            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/upload.blade.php
@extends('layouts.app')
@include('layouts.sidebar')
@section('content')
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
          <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Upload new Video</h4>

                                    <form method="post" action="{{ route('videos.store') }}" enctype="multipart/form-data">
                                      @csrf
                                    <div class="form-group">
                                      <input type="file" name="video" class="form-control-file" id="exampleFormControlFile1">
                                    </div>
                                    @if ($errors->has('video'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('video') }}</strong>
                                        </span>
                                        <br>
                                    @endif
                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                    <a href="{{ route('videos.index') }}"><button type="button" class="btn btn-danger waves-effect waves-light">Close</button></a>
                                    </form>

                                </div> <!-- end card body-->
                            </div> <!-- end card -->
                        </div><!-- end col-->
                    </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
{{-- <script src="{{ asset('js/metismenu.min.js') }}"></script>
<script src="{{ asset('js/waves.js') }}"></script> --}}
{{-- <script src="{{ asset('js/simplebar.min.js') }}"></script> --}}

<!-- third party js -->
        <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.flash.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.keyTable.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.select.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="{{ asset('pages/datatables-demo.js') }}"></script>
@endsection

resources/views/videos.blade.php
@extends('layouts.app')
@include('layouts.sidebar')
@section('content')
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
          <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-title">
                                      <h4>Content Manager ({{ count($videos) }})</h4>
                                      <div class="">
                                        <div class="form-group">
                                          <div class="row">
                                            <div class="col-sm-2">
                                              <label for="simpleinput">Search</label>
                                              <input type="text" id="title" class="form-control" placeholder="Enter your text">
                                            </div>
                                            <div class="col-sm-1">
                                              <label for="simpleinput">...........</label>
                                              <input type="button" onclick="search()" class="btn btn-primary" value="Search">
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>

                                    <table id="basic-datatable" class="table dt-responsive nowrap">
                                        <thead>
                                            <tr>
                                                <th>Thumbnail</th>
                                                <th>Name</th>
                                                <th>ID</th>
                                                <th>Created On</th>
                                                <th>Duration</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>


                                        <tbody id="tBody">
                                          @foreach ($videos as $video)
                                            <tr id="{{ $video['id'] }}">
                                              <td><img src="{{ asset($video->thumb) }}" height="60"/></td>
                                              <td>{{ $video['name'] }}</td>
                                              <td>{{ $video['id'] }}</td>
                                              <td>{{ $video['created_at'] }}</td>
                                              <td>{{ $video['duration'] }}</td>
                                              <td> <a href="/videos/{{ $video['id'] }}/edit"/><i class="feather-edit-2"></i></a> / <a onclick="deletevideo({{ $video['id'] }})"/><i class="mdi mdi-delete"></i></a></td>
                                            </tr>
                                          @endforeach
                                        </tbody>
                                    </table>

                                </div> <!-- end card body-->
                            </div> <!-- end card -->
                        </div><!-- end col-->
                    </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
{{-- <script src="{{ asset('js/metismenu.min.js') }}"></script>
<script src="{{ asset('js/waves.js') }}"></script> --}}
{{-- <script src="{{ asset('js/simplebar.min.js') }}"></script> --}}

<!-- third party js -->
        <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.flash.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.keyTable.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/dataTables.select.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="{{ asset('pages/datatables-demo.js') }}"></script>

        <script type="text/javascript">
          function deletevideo(e) {
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            var videoId = e;
            $.ajax({
                    /* the route pointing to the post function */
                    url: '/videos/'+videoId,
                    type: 'DELETE',
                    /* send the csrf-token and the input to the controller */
                    data: {_token: CSRF_TOKEN, deleteId: videoId},
                    dataType: 'JSON',
                    /* remind that 'data' is the response of the AjaxController */
                    success: function (data) {
                        if (data.status == 'success') {
                          $('#'+e).remove()
                        }
                    }
                });
          }

          function search(e) {
            var title = $('#title').val();
            if (title != '') {
              var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
              var apiToken = {{ json_encode(Auth::user()->api_token) }}
              $.ajax({
                      /* the route pointing to the post function */
                      url: '/api/videos/search',
                      headers: {
                                  'Authorization':'Bearer ' + apiToken,
                                },
                      type: 'POST',
                      /* send the csrf-token and the input to the controller */
                      data: {title: title},
                      dataType: 'JSON',
                      /* remind that 'data' is the response of the AjaxController */
                      success: function (data) {
                        var oldDom = $('<tbody/>').append($('#tBody').clone()).html();
                        // console.log(oldDom);
                          if (data.result) {
                            $('#tBody').empty();
                            var newTBody = '';
                            $.each(data.result, function (index, value) {
                              $('#tBody').append('<tr id='+ value.id +'><td><img src=/'+ value.thumb +' height="60"/></td><td>'+value.name+'</td><td>'+value.id+'</td><td>'+value.created_at+'</td><td>'+value.duration+'</td><td><a href="/videos/'+value.id+'/edit" class=feather-edit-2/></a> / <i onclick=deletevideo('+value.id+') class="mdi mdi-delete"></i></td></tr>');
                            });

                          }
                      }
                  });
            }
          }
        </script>
@endsection